config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  root to: "widgets#index"
  devise_for :users
  resources :memo_cards
  get "/pages/:page" => "pages#show"
  
  resources :posts do
    resources :comments
  end

  resources :memo_cards do
    member do
      get :check_answer
    end
    member do
      get :count_for_result
    end
  end

  resource :memo_cards do
    collection do
      get :get_new_status_for_user
    end
  end

  resource :memo_cards do
    collection do
      get :get_four_random_words
    end
  end

  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
  end

end

app/models/widget.rb
class Widget < ActiveRecord::Base

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if user_signed_in?
      redirect_to :controller => 'memo_cards', :action => 'index'
    end
  end


  def create_memo
    MemoCard.create(word: 'talTestFromPost', translation: 'test')
  end

end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h1 id="mainTitle">KooshKoosh learns Hebrew</h1>
<h2> now !</h2>
<div id="main-image"> <%= image_tag("s1.jpg", :alt => "rss feed", :class => "img-responsive" , :id =>"main-img") %> </div>
<h1 id="addition">   </h1>


<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.2.1/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.2.1/react-dom.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.34/browser.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/remarkable/1.6.2/remarkable.min.js"></script>

<div id="example"></div>
<script type="text/babel">
  ReactDOM.render(
     <h1>This is from react</h1>,
     document.getElementById('example')
   );

  var aboutZone = {
    title: "About",
    write: "Tal Shachar"
  }
  document.getElementById("addition").innerHTML = aboutZone.title;
</script>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>