config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  root to: "widgets#index"
  devise_for :users
  resources :memo_cards
  get "/pages/:page" => "pages#show"
  
  resources :posts do
    resources :comments
  end

  resources :memo_cards do
    member do
      get :check_answer
    end
    member do
      get :count_for_result
    end
  end

  resource :memo_cards do
    collection do
      get :get_new_status_for_user
    end
  end

  resource :memo_cards do
    collection do
      get :get_four_random_words
    end
  end

  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
  end

end

app/models/memo_card.rb
class MemoCard < ActiveRecord::Base
  has_many :posts
  attr_accessor :memo_card

  def is_memo_super_card?
    if memo_card.word == 'super'
      return true
    end
  end
end

app/controllers/memo_cards_controller.rb
require_relative '../../lib/answer_selector'
require_relative '../../lib/check_answers'
require_relative '../../lib/count_for_result'
require_relative '../../lib/user_status'
include AnswerSelector
include CheckAnswers
include CountForResult

class MemoCardsController < ApplicationController
  before_action :set_memo_card, only: [:show, :edit, :update, :destroy]

  attr_accessor :memo_card
  before_filter :authenticate_user!

  def index
    is_admin
    logger.debug 'Memo cards page'
    @memo_cards = MemoCard.all
    set_cookie
  end

  def get_four_random_words
     get_four_random_words_from_module(current_user, MemoCard, memo_card)
  end

  # TODO: get definition between words and phrases - add type of memo_card
  def show
    @random_array = get_four_random_words
    @word_id_array = MemoCard.select('id')
  end

  # GET /memo_cards/new
  def new
    @memo_card = MemoCard.new
  end

  # GET /memo_cards/1/edit
  def edit
  end

  def create
    @memo_card = MemoCard.new(memo_card_params)
    expire_page :action => :index
    respond_to do |format|
      if @memo_card.save
        format.html { redirect_to @memo_card, notice: 'Memo card was successfully created.' }
        format.json { render :show, status: :created, location: @memo_card }
      else
        format.html { render :new }
        format.json { render json: @memo_card.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    expire_page action: :index
    respond_to do |format|
      if @memo_card.update(memo_card_params)
        format.html { redirect_to @memo_card, notice: 'Memo card was successfully updated.' }
        format.json { render :show, status: :ok, location: @memo_card }
      else
        format.html { render :edit }
        format.json { render json: @memo_card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @memo_card.destroy
    respond_to do |format|
      format.html { redirect_to memo_cards_url, notice: 'Memo card was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  def check_answer
    session_id = session[:session_id]
    is_admin = params[:dbg_mode]
    result = check_answer_from_module(params[:word_temp], params[:word_in_german], current_user, session_id, is_admin)
    respond_to do |format|
       format.json { render json: {answer:result[0], nextid:result[1]} }
     end
  end

  def count_for_result
    session_id = session[:session_id]
    is_admin = params[:dbg_mode]
    count_for_result_from_module(current_user, session_id, is_admin)
  end

  def get_new_status_for_user
    current_user_id = current_user.id
    result = get_new_status_for_user_from_module(@memo_cards, current_user_id)
    respond_to do |format|
      format.json { render json: {counter: result[0]} }
    end
  end

  private
    def set_memo_card
      @memo_card = MemoCard.find(params[:id])
    end

    def memo_card_params
      params.require(:memo_card).permit(:word, :translation, :word_id, :lang_id)
    end

    def is_admin
      admin = params[:admin]
      if admin == "true"
        puts "Admin mode"
      end
    end

    def set_cookie
      cookies[:user_id] = current_user.id
    end
end

app/helpers/memo_cards_helper.rb
module MemoCardsHelper
end

app/views/memo_cards/_form.html.erb
<%= form_for(@memo_card) do |f| %>
  <% if @memo_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memo_card.errors.count, "error") %> prohibited this memo_card from being saved:</h2>

      <ul>
      <% @memo_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :translation %><br>
    <%= f.text_field :translation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
    <div class="field">
      <%=f.hidden_field :lang_id, :value => @current_user.user_type  %>
    </div>
<% end %>

app/views/memo_cards/_random_card.html.erb
<p> this is render partial </p>

<p>
  <strong>Word:</strong>
</p>
<p id="question"> <%= @memo_card.word %> </p>

<table>
  <td id="answer1" class="answer"> <%= @random_array.first  %> </td>
  <td id="answer2" class="answer"> <%= @random_array.second  %> </td>
  <td id="answer3" class="answer"> <%= @random_array.third  %> </td>
  <td id="answer4" class="answer"> <%= @random_array.fourth  %> </td>
</table>

<%= link_to 'Back', memo_cards_path %>

app/views/memo_cards/edit.html.erb
<h1>Editing memo_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @memo_card %> |
<%= link_to 'Back', memo_cards_path %>

app/views/memo_cards/index.html.erb
<br>
<table id="newDesign">
  <thead id="tableHead">
    <tr>
      <th>Word:</th>
      <th>Word status: </th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody >
  <div hidden="true"> <%= user_type_id = User.select("user_type").where(email: current_user.email) %> </div>
    <% @memo_cards.where(lang_id: user_type_id).each do |memo_card| %>
      <tr>
        <td><%= memo_card.word %> &nbsp &nbsp </td>
        <td id="statusBar" class="hidden"> <%= @counterer = (Results.select("word_id").where(word_id: memo_card.id , user_id: current_user.id , is_correct: 1 , created_at: 3.weeks.ago..Time.now)).length %> </td>
        <%     if (@counterer.to_i > 0 and @counterer < 3)       %>
        <%           @counterer_status = "More Practice"         %>
        <%     elsif  (@counterer.to_i == 0 )                       %>
        <%          @counterer_status = "New word! or forgotten.."              %>
        <%     else                                              %>
        <%          @counterer_status = "You Know it"            %>
        <%     end                                               %>
        <td id="realStatus">     <%=  @counterer_status %> </td>
        <td> &nbsp &nbsp &nbsp &nbsp </td>
        <td><%= link_to 'Test yourself ', memo_card %>  </td>
        <td> &nbsp &nbsp &nbsp &nbsp </td>
        <% if (current_user.admin?) %>
            <td><%= link_to 'Edit ', edit_memo_card_path(memo_card) %></td>
        <% end %>
        <td> &nbsp  &nbsp  &nbsp &nbsp</td>
        <% if (current_user.admin?) %>
            <td><%=link_to 'Delete', memo_card, method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <% end %>
        <td> &nbsp </td>
      </tr>
    <% end %>
  </tbody>
</table>
    <table id="user_stats">
      <tbody>
         <h3> User stats: </h3>
         <tr>
            <td>  <h4> correct answers: <%= ($redis.get("correct_answers_for_user_" + current_user.id.to_s)).to_i %> </h4> </td>
            <td> <h4> wrong answers: <%= ($redis.get("wrong_answers_for_user_" + current_user.id.to_s)).to_i %> </h4> </td>
         </tr>
             <h4> last login: <%= current_user.last_sign_in_at %> </h4>
      </tbody>
     <table>
<br>

<%= link_to 'New Memo card', new_memo_card_path, :id => "create_new_memo_card"  %>

app/views/memo_cards/new.html.erb
<h1>New memo_card</h1>

<%= render 'form' %>

<%= link_to 'Back', memo_cards_path %>

app/views/memo_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
</p>
  <div id="container">
      <h2> <p id="question"> <%= @memo_card.word %> </p> </h2>
        <table id="table-format" data-toggle="table" class="table" border="2">
          <abbr> <td id="answer1" class="answer"> <%= @random_array.first %> </td> </abbr>
          <abbr> <td id="answer2" class="answer"> <%= @random_array.second  %> </td> </abbr>
          <td id="answer3" class="answer"> <%= @random_array.third  %> </td>
          <td id="answer4" class="answer"> <%= @random_array.fourth  %> </td>
         </table>
      </p>
  </div>

<div id="theAnswerIs">    <a href="#" class="close" data-dismiss="alert" id="theAnswerIs">&times;</a> </div>
    <div id="myAlert" class="alert alert-warning">
        <strong>Choose the correct answer!</strong>
       <div id="results">    </div>
       <div id="calculate"> calculate your daily result </div>
</div>
<p>
</p>

<%= link_to 'Edit memo card', edit_memo_card_path(@memo_card) %> |
<%= link_to 'Back to vocabulary', memo_cards_path %>